### ISSUE TITLE
Zeppelin returns errors in some methods, possible Scala version conflict?

### ISSUE THREAD

**Issue by jmrr** [NLP4L/attic-nlp4l#29]
Hi,

I have Zeppelin installed on a Centos 7 docker container compiled with Maven and using Scala 2.10. I tried to run your Zeppelin visualizations, which run perfectly on the NLP4L REPL after I clone your repo and build with sbt which I believe uses Scala 2.11.

However when I issue the command `status` on a Zeppelin paragraph with the `%nlp4l` interpreter I get the following error (open of the Luce index works fine)

```
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
    at org.nlp4l.core.RawReader.fieldMap$lzycompute(RawReader.scala:46)
    at org.nlp4l.core.RawReader.fieldMap(RawReader.scala:40)
    at org.nlp4l.core.RawReader.fields(RawReader.scala:53)
    at org.nlp4l.repl.NLP4L$.displayIndexInfo(NLP4L.scala:221)
    at org.nlp4l.repl.NLP4L$.status(NLP4L.scala:198)
    at .<init>(<console>:53)
    at .<clinit>(<console>)
    at .<init>(<console>:7)
    at .<clinit>(<console>)
    at $print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
    at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
    at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
    at org.nlp4l.zeppelin.NLP4LInterpreter.interpretInput(NLP4LInterpreter.java:177)
    at org.nlp4l.zeppelin.NLP4LInterpreter.interpret(NLP4LInterpreter.java:156)
    at org.nlp4l.zeppelin.NLP4LInterpreter.interpret(NLP4LInterpreter.java:151)
    at org.apache.zeppelin.interpreter.ClassloaderInterpreter.interpret(ClassloaderInterpreter.java:57)
    at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:93)
    at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:277)
    at org.apache.zeppelin.scheduler.Job.run(Job.java:170)
    at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:118)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

It also breaks when running
`val allMap = WordCounts.count(reader, "body", Set.empty, allDS, -1, analyzer)`

giving the following 

```
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
    at org.nlp4l.core.TermVector.terms$lzycompute(TermVector.scala:41)
    at org.nlp4l.core.TermVector.terms(TermVector.scala:31)
    at org.nlp4l.stats.WordCounts$$anonfun$count$1.apply(WordCounts.scala:62)
    at org.nlp4l.stats.WordCounts$$anonfun$count$1.apply(WordCounts.scala:59)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:84)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)
    at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:151)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.immutable.TreeSet.scala$collection$SetLike$$super$map(TreeSet.scala:51)
    at scala.collection.SetLike$class.map(SetLike.scala:93)
    at scala.collection.immutable.TreeSet.map(TreeSet.scala:51)
    at org.nlp4l.stats.WordCounts$.count(WordCounts.scala:59)
    at .<init>(<console>:56)
    at .<clinit>(<console>)
    at .<init>(<console>:7)
    at .<clinit>(<console>)
    at $print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
    at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
    at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
    at org.nlp4l.zeppelin.NLP4LInterpreter.interpretInput(NLP4LInterpreter.java:177)
    at org.nlp4l.zeppelin.NLP4LInterpreter.interpret(NLP4LInterpreter.java:156)
    at org.nlp4l.zeppelin.NLP4LInterpreter.interpret(NLP4LInterpreter.java:151)
    at org.apache.zeppelin.interpreter.ClassloaderInterpreter.interpret(ClassloaderInterpreter.java:57)
    at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:93)
    at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:277)
    at org.apache.zeppelin.scheduler.Job.run(Job.java:170)
    at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:118)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

I'm no Scala expert but I suspect the error might be there. Any ideas of how can be fixed? 

Thanks!!

**Comment by kojisekig** [comment]
Thank you for reporting this!

As you've told in the title, it may be Scala version conflict as long as I googled the error message you've posted. But I'm not sure it is the reason of this problem.

I don't have any idea to solve this problem without removing version conflict...
